/*******************************************************************************
 * Copyright (c) 2015 Low Latency Trading Limited  :  Author Richard Rose
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at	http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing,  software distributed under the License 
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_net_SocketOptions */

#ifndef _Included_java_net_SocketOptions
#define _Included_java_net_SocketOptions
#ifdef __cplusplus
extern "C" {
#endif
#undef java_net_SocketOptions_TCP_NODELAY
#define java_net_SocketOptions_TCP_NODELAY 1L
#undef java_net_SocketOptions_SO_BINDADDR
#define java_net_SocketOptions_SO_BINDADDR 15L
#undef java_net_SocketOptions_SO_REUSEADDR
#define java_net_SocketOptions_SO_REUSEADDR 4L
#undef java_net_SocketOptions_SO_BROADCAST
#define java_net_SocketOptions_SO_BROADCAST 32L
#undef java_net_SocketOptions_IP_MULTICAST_IF
#define java_net_SocketOptions_IP_MULTICAST_IF 16L
#undef java_net_SocketOptions_IP_MULTICAST_IF2
#define java_net_SocketOptions_IP_MULTICAST_IF2 31L
#undef java_net_SocketOptions_IP_MULTICAST_LOOP
#define java_net_SocketOptions_IP_MULTICAST_LOOP 18L
#undef java_net_SocketOptions_IP_TOS
#define java_net_SocketOptions_IP_TOS 3L
#undef java_net_SocketOptions_SO_LINGER
#define java_net_SocketOptions_SO_LINGER 128L
#undef java_net_SocketOptions_SO_TIMEOUT
#define java_net_SocketOptions_SO_TIMEOUT 4102L
#undef java_net_SocketOptions_SO_SNDBUF
#define java_net_SocketOptions_SO_SNDBUF 4097L
#undef java_net_SocketOptions_SO_RCVBUF
#define java_net_SocketOptions_SO_RCVBUF 4098L
#undef java_net_SocketOptions_SO_KEEPALIVE
#define java_net_SocketOptions_SO_KEEPALIVE 8L
#undef java_net_SocketOptions_SO_OOBINLINE
#define java_net_SocketOptions_SO_OOBINLINE 4099L
#ifdef __cplusplus
}
#endif
#endif
