/*******************************************************************************
 * Copyright (c) 2015 Low Latency Trading Limited  :  Author Richard Rose
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at	http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing,  software distributed under the License 
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_IOStatus */

#ifndef _Included_sun_nio_ch_IOStatus
#define _Included_sun_nio_ch_IOStatus
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_nio_ch_IOStatus_EOF
#define sun_nio_ch_IOStatus_EOF -1L
#undef sun_nio_ch_IOStatus_UNAVAILABLE
#define sun_nio_ch_IOStatus_UNAVAILABLE -2L
#undef sun_nio_ch_IOStatus_INTERRUPTED
#define sun_nio_ch_IOStatus_INTERRUPTED -3L
#undef sun_nio_ch_IOStatus_UNSUPPORTED
#define sun_nio_ch_IOStatus_UNSUPPORTED -4L
#undef sun_nio_ch_IOStatus_THROWN
#define sun_nio_ch_IOStatus_THROWN -5L
#undef sun_nio_ch_IOStatus_UNSUPPORTED_CASE
#define sun_nio_ch_IOStatus_UNSUPPORTED_CASE -6L
#ifdef __cplusplus
}
#endif
#endif
