/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hal_smt2_core_os_NativeHooksImpl */

#ifndef _Included_hal_smt2_core_os_NativeHooksImpl
#define _Included_hal_smt2_core_os_NativeHooksImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hal_smt2_core_os_NativeHooksImpl
 * Method:    jniCalibrateTicks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hal_smt2_core_os_NativeHooksImpl_jniCalibrateTicks
  (JNIEnv *, jclass);

/*
 * Class:     hal_smt2_core_os_NativeHooksImpl
 * Method:    jniSetPriority
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_hal_smt2_core_os_NativeHooksImpl_jniSetPriority
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     hal_smt2_core_os_NativeHooksImpl
 * Method:    jniSleep
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hal_smt2_core_os_NativeHooksImpl_jniSleep
  (JNIEnv *, jclass, jint);

/*
 * Class:     hal_smt2_core_os_NativeHooksImpl
 * Method:    jniSleepMicros
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hal_smt2_core_os_NativeHooksImpl_jniSleepMicros
  (JNIEnv *, jclass, jint);

/*
 * Class:     hal_smt2_core_os_NativeHooksImpl
 * Method:    jniSetProcessMaxPriority
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hal_smt2_core_os_NativeHooksImpl_jniSetProcessMaxPriority
  (JNIEnv *, jclass);

/*
 * Class:     hal_smt2_core_os_NativeHooksImpl
 * Method:    jniNanoTimeRDTSC
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_hal_smt2_core_os_NativeHooksImpl_jniNanoTimeRDTSC
  (JNIEnv *, jclass);

/*
 * Class:     hal_smt2_core_os_NativeHooksImpl
 * Method:    jniNanoTimeMonotonicRaw
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_hal_smt2_core_os_NativeHooksImpl_jniNanoTimeMonotonicRaw
  (JNIEnv *, jclass);

/*
 * Class:     hal_smt2_core_os_NativeHooksImpl
 * Method:    jniNanoRDTSCStart
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_hal_smt2_core_os_NativeHooksImpl_jniNanoRDTSCStart
  (JNIEnv *, jclass);

/*
 * Class:     hal_smt2_core_os_NativeHooksImpl
 * Method:    jniNanoRDTSCStop
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_hal_smt2_core_os_NativeHooksImpl_jniNanoRDTSCStop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
